add max min abs
plum-umd/the-838e-compiler pull request #57
Opened 2021-02-24 08:26 UTC by minghui-liu

2021-02-24 13:09 UTC, dvanhorn requested changes

2021-02-24 13:09 UTC, dvanhorn commented on villain/lib/math.rkt
> +(define (max . xs)
these should take at least one argument and not use a max/min constant.

2021-02-24 14:10 UTC, dvanhorn commented
I touched up `min` and `max`, but this needs test cases before I accept.

2021-02-25 19:29 UTC, minghui-liu commented
Thanks for the changes. I've modified the interpreter and added tests.

2021-02-25 21:47 UTC, merged